### ISSUE TITLE
Ejercicio correcto solo con un git status

### ISSUE THREAD

**Issue by mesaglio** [MumukiProject/mumuki-guia-text-archivos-repositorios-y-versiones#2]
Con un git status lo marca como resuelto. Si intentas ver el log tampoco te muestra el commit.
![image](https://user-images.githubusercontent.com/29051129/61012372-a7d75c00-a354-11e9-9e01-d9e18d4c47d6.png)

**Comment by flbulgarelli** [comment]
@Gustrucco esto parece ser un tema de que el ejercicio está mal planteado.

**Comment by Gustrucco** [comment]
Ahí probé y no pude replicar el problema.
